### ISSUE TITLE
Happy Birthday!

### ISSUE THREAD

**Issue by DirectDuck** [maximilionus/Telemonitor#2]
![80a498fcc3a5f869d1ba341da46d5e80](https://user-images.githubusercontent.com/43792301/89270897-a73af300-d644-11ea-9a9a-55530a0c4fe1.jpg)

**Comment by maximilionus** [comment]
![8BF19AE3-2D97-4FA7-ACA2-B2CA79904B30](https://user-images.githubusercontent.com/29492157/89285503-2d613480-d659-11ea-998a-82db6d62fa97.jpeg)

Вот это я понимаю - крепкое программерское поздравление. Thank you, sir.
