### ISSUE TITLE
🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳

### ISSUE THREAD

**Issue by DirectDuck** [maximilionus/Telemonitor#3]
### **ПОБЕДИЛ**
![win](https://user-images.githubusercontent.com/43792301/144000300-c594cba0-469d-4f00-ad02-10c67cc1df52.gif)

**Comment by maximilionus** [comment]
![gosling-rayan-gosling](https://user-images.githubusercontent.com/29492157/157347731-1c8235cc-5d6b-4819-9e37-c24b834ba83a.gif)
